# coding: utf-8

"""
    Event Streams for Apache Kafka API

    A managed Apache Kafka cluster is designed to be highly fault-tolerant and scalable, allowing large volumes of data to be ingested, stored, and processed in real-time. By distributing data across multiple brokers, Kafka achieves high throughput and low latency, making it suitable for applications requiring real-time data processing and analytics. 

    The version of the OpenAPI document: 1.8.0
    Contact: support@cloud.ionos.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from ionoscloud_kafka.models.kafka_cluster_connection import KafkaClusterConnection
from typing import Optional, Set
from typing_extensions import Self

class Cluster(BaseModel):
    """
    A Kafka cluster that stores data and serve client requests. Kafka clusters typically have multiple brokers to handle more data and provide high availability. Each broker is identified by a unique ID and manages partitions of different topics. 
    """ # noqa: E501
    name: Optional[Annotated[str, Field(min_length=2, strict=True, max_length=63)]] = Field(default=None, description="The name of your Kafka cluster. Must be 63 characters or less and must begin and end with an alphanumeric character (`[a-z0-9A-Z]`) with dashes (`-`), underscores (`_`), dots (`.`), and alphanumerics between. ")
    version: Optional[Annotated[str, Field(strict=True, max_length=32)]] = Field(default=None, description="The version of Kafka. Allowed values are `3.7.0` and `3.8.0`. Deprecation Warning: `3.7.0` will be removed end of May 2025. ")
    size: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="The size of your Kafka cluster. The size of the Kafka cluster is given in T-shirt sizes. Valid values are: `XS`, `S`, `M`, `L`, and `XL`. ")
    connections: Optional[Annotated[List[KafkaClusterConnection], Field(min_length=1, max_length=1)]] = None
    __properties: ClassVar[List[str]] = ["name", "version", "size", "connections"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Cluster from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in connections (list)
        _items = []
        if self.connections:
            for _item_connections in self.connections:
                if _item_connections:
                    _items.append(_item_connections.to_dict())
            _dict['connections'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Cluster from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "version": obj.get("version"),
            "size": obj.get("size"),
            "connections": [KafkaClusterConnection.from_dict(_item) for _item in obj["connections"]] if obj.get("connections") is not None else None
        })
        return _obj


